# Generated by Django 3.2.18 on 2023-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=30)),
                ('weather', models.CharField(max_length=30)),
            ],
        ),
    ]
