# Generated by Django 3.2.12 on 2023-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
