# Generated by Django 3.2.12 on 2023-04-16 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musics', '0002_alter_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='like_users',
            field=models.ManyToManyField(related_name='like_musics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
